[build]
packages = [
    "pyroll" # place your package in the pyroll namespace
]

[version]
path = "pyroll/linear_thermal_expansion.py"

[envs.default]
path = ".venv"
dependencies = [
    "pytest ~= 7.0",
    "pyroll-integral-thermal ~= 2.0",
]

[envs.test]
path = ""

[envs.test.scripts]
all = "pytest"

[[envs.test.matrix]]
python = ["3.9", "3.10", "3.11"]